spring:
  profiles:
    include: jwt, email, aws, oauth , mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        alect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        default_batch_fetch_size: 1000
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  data:
    web:
      pageable:
        default-page-size: 30

server:
  servlet:
    session:
      tracking-modes: cookie
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error