spring:
  profiles:
    include: jwt, email, aws, oauth
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  data:
    web:
      pageable:
        default-page-size: 30

server:
  servlet:
    session:
      tracking-modes: cookie
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error